---
title: "psychencode_xiaolin_figure"
author: "Daniel Kiss"
date: "7/30/2024"
output: html_document
---
Load data
```{r}
merged_df <- readRDS(file = "/external/rprshnas01/netdata_kcni/stlab/Xiaolin/cell_deconv_data/data/Fig1A_scatterplot_merged_df.RData")
df <-readRDS(file = "/external/rprshnas01/netdata_kcni/stlab/Xiaolin/cell_deconv_data/data/correlation_barplot_danpaper_MGP.RData") 
```
 
Plots
```{r, fig.height= 10, fig.width=10}
figure_X1a <- merged_df %>%
  ggplot(aes(x = snCTP*100, y = rCTP)) +
  geom_smooth(se = FALSE, method = 'lm', fullrange = TRUE) +
  stat_cor(aes(label = paste(..r.label.., ..p.label.., sep = "~")), color = "black", geom = "label", size=10, label.y=3)+
  geom_point(alpha = 1, size = 3, color="black") +
  ylab('rCTP (AU)') + 
  xlab('snCTP (%)') +
  theme(
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    strip.background = element_rect(fill = "white", colour = "black"),
    axis.line = element_line(color = "black"),
    axis.text.x = element_text(size = 32),
    axis.text.y = element_text(size = 32),
    axis.title.x = element_text(vjust = -3,size = 32),
    plot.margin = margin(1, 1, 1, 1, "cm"),
    axis.title.y = element_text(size = 32),
    legend.position = c(0.9, 0.9),
    legend.title = element_blank(),
    legend.text = element_text(size = 32),
    strip.text.x = element_text(size = 32)
  ) +
  facet_grid(~cell_type, scale="free_x") +
  theme(panel.spacing = unit(1, "cm", data = NULL))
  # +
  #scale_y_continuous(limits = c(-4, 4))

theme_set(theme_classic2())
#Colour palette
cbPalette = c("#56B4E9", "#009E73","#E69F00", "#0072B2", "#D55E00", "#CC79A7","#000000","#F0E442")

figure_X1b <- df %>% 
  ggplot(aes(x = Name, y = Accuracy)) + 
  geom_hline(yintercept = 0) + 
  geom_bar(stat = "identity", position = "dodge") + 
  geom_errorbar(aes(ymin = SE_Lower, ymax = SE_Upper)) +
  facet_grid(~Label, scales = "free", space = "free_x") +
  geom_hline(yintercept = 0.2, color = "red", linewidth=1.5) + 
  ylab("Pearson's R") + 
  xlab('Cell Types') + 
  theme(
    panel.background = element_blank(),  # Keeps the panel background transparent
    panel.grid.major = element_blank(),  # Removes major grid lines
    panel.grid.minor = element_blank(),  # Removes minor grid lines
    strip.background = element_rect(fill = "white", colour = "black"),
    axis.line = element_line(color = "black"),  # Ensures x-axis and y-axis lines are visible
    axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1, size = 30),
    axis.text.y = element_text(size = 32),
    axis.title.x = element_text(vjust = 8, size = 32),
    axis.title.y = element_text(size = 32),
    strip.text.x = element_text(size = 30)
  ) +
  guides(fill = FALSE) +
  scale_y_continuous(limits = c(-0.35, 0.7)) 

figure_X1 = figure_X1a / figure_X1b
figure_X1 = figure_X1 + plot_annotation(tag_levels = 'A') + plot_layout(heights = c(2,1)) & theme(plot.tag = element_text(size = 25))
figure_X1

#Save to plots folder
output_filename <- "~/cell_prop_psychiatry/plots/figure_X1.jpg"

# Use ggsave to save the plot as a JPG image
ggsave(output_filename, figure_X1, width = 10, height = 10, dpi = 500)
```
 
