---
title: "differential_expression_tutorial"
author: "Daniel Kiss"
date: "6/6/2023"
output: html_document
---

Load Packages etc.
```{r}
library(dplyr)
library(tidyverse)
library(edgeR)
library(markerGeneProfile) 
library(matrixStats)
library(cowplot)
library(broom)
library(knitr)
library(ggpubr)
library(biomaRt)
library(ggrepel)
library(patchwork)
library(ggsignif)
library(modelr)
library(ggbeeswarm)
library(lemon)
theme_set(theme_classic2())
#Colour palette
cbPalette <- c("#56B4E9", "#009E73","#E69F00", "#0072B2", "#D55E00", "#CC79A7","#000000","#F0E442")
```


```{r}
counts = read.delim("/external/rprshnas01/kcni/dkiss/cell_prop_psychiatry/DE_Tutorial/all_counts.txt", row.names = 1)
#Create DGEList object and add normalization factors
d0 <- DGEList(counts) %>% calcNormFactors()
#Filter low-expressed genes
cutoff <- 1
drop <- which(apply(cpm(d0), 1, max) < cutoff)
d <- d0[-drop,] 
dim(d) # number of genes left

#Our experiment has two factors, cultivar (“C”, “I5”, or “I8”) and time (6 or 9). The sample names are the cultivar, followed by the time, followed by the replicate
snames <- colnames(counts)
cultivar <- substr(snames, 1, nchar(snames) - 2) 
time <- substr(snames, nchar(snames) - 1, nchar(snames) - 1)
group <- interaction(cultivar, time)

plotMDS(d, col = as.numeric(group))
```

Voom transformation and calculation of variance weights
```{r}
#Specify the model to be fitted. We do this before using voom since voom uses variances of the model residuals (observed - fitted)
mm <- model.matrix(~0 + group )
y <- voom(d, mm, plot = T)
#A good voom plot will have very few points at X = 0
```

Fitting linear models in limma
```{r}
#lmFit fits a linear model using weighted least squares for each gene:
fit <- lmFit(y, mm)
head(coef(fit))
#Comparison between times 6 and 9 for cultivar I5
contr <- makeContrasts(groupI5.9 - groupI5.6, levels = colnames(coef(fit)))
contr
#Estimate contrast for each gene
tmp <- contrasts.fit(fit, contr)
#Empirical Bayes smoothing of standard errors (shrinks standard errors that are much larger or smaller than those from other genes towards the average standard error) (see https://www.degruyter.com/doi/10.2202/1544-6115.1027)
tmp <- eBayes(tmp)
#What genes are most differentially expressed?
top.table <- topTable(tmp, sort.by = "P", n = Inf)
head(top.table, 20)
#How many DE genes are there?
length(which(top.table$adj.P.Val < 0.05))
#Write top.table to a file
top.table$Gene <- rownames(top.table)
top.table <- top.table[,c("Gene", names(top.table)[1:6])]
write.table(top.table, file = "time9_v_time6_I5.txt", row.names = F, sep = "\t", quote = F)
```

